steps:

# Clone the repo
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/hutomadotAI/web-console.git']
  
# Build the docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', 'eu.gcr.io/hutoma-backend/web/mediaserver:$BRANCH_NAME-$SHORT_SHA',
         '-t', 'eu.gcr.io/hutoma-backend/web/mediaserver:latest',
         'src']

# Push the image to the internal repo
images: ['eu.gcr.io/hutoma-backend/web/mediaserver:$BRANCH_NAME-$SHORT_SHA',
         'eu.gcr.io/hutoma-backend/web/mediaserver:latest']
