# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_migrate_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dev_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
    ]
