# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 16:02
from __future__ import unicode_literals

from django.db import migrations

from users.hashers import PBKDF2WrappedSHA256PasswordHasher


def forwards_func(apps, schema_editor):
    """
    Migrate a collection of SHA256 hashes to use PBKDF2(SHA256(password))
    """
    User = apps.get_model('auth', 'User')
    users = User.objects.filter(password__startswith='sha256$')
    hasher = PBKDF2WrappedSHA256PasswordHasher()
    for user in users:
        algorithm, salt, sha256_hash = user.password.split('$', 2)
        user.password = hasher.encode_sha256_hash(sha256_hash, salt)
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_uuid'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
