# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=64)),
                ('password_salt', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=30)),
                ('created', models.DateTimeField()),
                ('attempt', models.CharField(max_length=15)),
                ('dev_token', models.CharField(max_length=250)),
                ('plan_id', models.IntegerField()),
                ('dev_id', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('valid', models.IntegerField()),
                ('internal', models.IntegerField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
