apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        service: nginx
    spec:
      containers:
        - name: nginx
          image: "nginx:1.13.3"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-conf"
              mountPath: "/etc/nginx/conf.d"
      volumes:
        - name: "nginx-conf"
          configMap:
            name: "nginx-conf"
            items:
              - key: "nginx.conf"
                path: "nginx.conf"
