kind: Service
apiVersion: v1
metadata:
  name: "nginx"
spec:
  selector:
    service: "nginx"
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
    # VPN
    # - 104.199.96.106/32
    # - 10.8.0.0/16
    # - 10.132.0.0/16


