# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1024)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('alert_message', models.CharField(blank=True, max_length=150, null=True)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('license_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sample', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('privacy_policy', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=25)),
                ('video_link', models.CharField(blank=True, max_length=1800, null=True)),
                ('publishing_state', models.IntegerField()),
                ('boticon', models.CharField(blank=True, db_column='botIcon', max_length=255, null=True)),
                ('featured', models.IntegerField()),
            ],
            options={
                'db_table': 'botStore',
                'managed': False,
            },
        ),
    ]
